# Definição da imagem que vamos utilizar, nesse caso para React usamos o Node.js
image: node:20.18.0

definitions:
  steps:
    - step: &githubpage
        name: Deploy to GitHub Pages
        script:
          - echo "Setting up SSH agent"
          - mkdir -p ~/.ssh
          - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa
          - ssh-keyscan github.com >> ~/.ssh/known_hosts

          - echo "Cloning GitHub repository"
          - git clone git@github.com:FluxusTech0/TesteGithubPage.git
          - cd repositorio-gh-pages

          - echo "Atualizando conteúdo"
          # Adicione comandos aqui para compilar/gerar o conteúdo da página
          # por exemplo, npm run build

          - echo "Fazendo push das alterações"
          - git add .
          - git commit -m "Atualização via Bitbucket pipeline"
          - git push origin main  # ou a branch que estiver usandoo

pipelines:
  # Regra para executar o pipeline em pull requests
  pull-requests:
    '**':
      - step: *githubpage